import re
import html

def vis_count(raw):
    decoded = html.unescape(raw)
    stripped = re.sub(r'<[^>]+>', ' ', decoded)
    stripped = stripped.replace('\n', ' ').replace('\t', ' ')
    stripped = re.sub(r'\s+', ' ', stripped).strip()
    return len(stripped), stripped

notes = [
    (1778251562563, "dysregulated host response to infection | ≥2 points\n→ CCRN KEY: SOFA assesses: respiratory (P/F), coagulation (platelets), liver (bilirubin), cardiovascular (MAP/vasopressors), CNS (GCS), renal (creatinine/UO).", "Sepsis-3 definition: life-threatening organ dysfunction..."),
    (1778251562565, "vasopressor requirement to maintain MAP ≥65 | lactate >2 mmol/L\n→ CCRN KEY: Septic shock mortality 40–50%. Lactate >4 = high mortality, mandate ICU admission. Lactate clearance (>10% in 2h) is a resuscitation endpoint.", "Septic shock definition: sepsis plus..."),
    (1778251562567, "1) Measure lactate 2) Blood cultures × 2 (before antibiotics) 3) Broad-spectrum antibiotics 4) 30 mL/kg IV crystalloid if hypotensive/lactate ≥4 5) Vasopressors for MAP &lt;65\n→ CCRN KEY: Time-sensitive: each hour delay in antibiotics increases mortality. CXR, UA, cultures from all possible sources before antibiotics if possible.", "SSC Hour-1 Bundle 5 actions..."),
    (1778251562569, "norepinephrine | 0.01–0.5 mcg/kg/min (titrate to MAP ≥65)\n→ CCRN KEY: Norepinephrine preferred over dopamine (SOAP II trial: dopamine → more arrhythmias, possible worse mortality). Add vasopressin 0.03–0.04 units/min as adjunct to reduce norepinephrine dose.", "First-line vasopressor in septic shock..."),
    (1778251562571, "vasopressors cannot maintain MAP ≥65 despite adequate fluids (vasopressor-refractory shock)\n→ CCRN KEY: APROCCHSS trial: hydrocortisone + fludrocortisone → faster shock reversal, more ventilator-free days. Do NOT wait for cortisol stimulation test results.", "Corticosteroids (hydrocortisone 200 mg/day) added when..."),
    (1778251562573, "support diagnosis of bacterial infection | guide de-escalation (stop antibiotics when PCT falls ≥80% from peak or absolute &lt;0.5 ng/mL)\n→ CCRN KEY: PCT rises in bacterial sepsis, minimally in viral/fungal/autoimmune. PCT-guided antibiotic stewardship → less antibiotic days without worse outcomes.", "Procalcitonin (PCT) is used in sepsis to..."),
    (1778251562575, "lymphopenia, monocyte deactivation (low HLA-DR), secondary infections | treat underlying infections, ICU prevention bundles (VAP, CLABSI, CAUTI bundles)\n→ CCRN KEY: Survivors of initial sepsis may die from secondary HAI. Immunomodulatory therapy (IL-7, GM-CSF) under investigation.", "Sepsis-related immunosuppression (late sepsis)..."),
    (1778251562577, "MAP ≥65 mmHg | MAP ≥75–80 mmHg (chronic hypertension organs autoregulate at higher baseline)\n→ CCRN KEY: 65MAP target standard (SEPSISPAM trial). Higher MAP may benefit patients with pre-existing hypertension but ↑ arrhythmias.", "In septic shock, target MAP is..."),
    (1778251562579, "balanced crystalloids (LR or PlasmaLyte) | normal saline at large volumes (hyperchloremic metabolic acidosis + AKI risk)\n→ CCRN KEY: SMART trial: balanced crystalloids → lower rate of major kidney events vs. NS. Albumin may be used in severe sepsis (SAFE trial: no harm), especially if albumin &lt;2.", "Fluid resuscitation in sepsis: use..."),
    (1778251562581, "dynamic measures: pulse pressure variation (PPV >13%), stroke volume variation (SVV >10%), passive leg raise (PLR) test\n→ CCRN KEY: PLR: raise legs 45° for 1 min → if CO ↑ ≥10% = fluid responsive. More reliable than CVP (CVP alone should NOT guide fluid therapy).", "Sepsis bundle monitoring: reassess fluid responsiveness..."),
    (1778251562583, "Hypertensive emergency/crisis: elevated BP with evidence of end organ damage (brian, heart, kidney, retina) that cn be related to acute HTNHypertensive urgency: elevated BP without evidence of acute end organ damage. Usually no need for critical care admission.", "Difference between hypertensive emergency/crisis and urgency?"),
    (1778251562585, "4–8mmHg. CVP increases with increased blood in the venous system, which increases diastolic filling pressure and therefore SV.", "Normal CVP range? What makes it increase?"),
    (1778251562587, "The phlebostatic axis. It reads 2mmHg above the actual pressure for every inch it is below the phlebostatic axis, and 2mmHg below the actual pressure for every inch it is above. It is most accurate if the pt is flat.", "ART line transducer level with?"),
    (1778251562589, "Test to assess for peripheral artery disease. Divide the ankle pressure by the crachial pressure on the same side. Normal is >0.90.", "What is the ankle-brachial index?"),
    (1778251562591, "Do not elevate the extremity, this will decrease blood flow even more.", "Avoid if peripheral artery disease?"),
    (1778251562593, "Flat or reverse trendelenburg. And have them breath out, or, \"blow out the candles\" when you pull it. This prevent air embolism.", "Position when pulling CVC from IJ?"),
    (1778251562595, "Right Ventricular Systolic Pressure. It's a measurement of the pressure generated by the right ventricle when it pumps. It assesses for pulmonary HTN. If under 50, normal RSVP IS 16–39mmHg. 50–75 is 15–45. Greater than 75 is 17–52. It increases with age, but over 40 is generally considered elevated.", "What is RVSP? What is considered normal?"),
    (1778251562597, "The movement of air in and out of the body to maintain appropriate concentrations of O2 and CO2. The primary, central, control is the brainstem. It senses pH — with acidosis, or a decrease in pH, rate/depth of breathing increase to correct it. Secondary, peripheral, control is PaO₂ \"sensors\" in the aortic arch. Decreased PaO₂ = hypoxemia, which results in increase in rate/depth of breathing.", "What is ventilation? Primary and secondary control?"),
    (1778251562599, "Ventilation/perfusion ratio. 4L ventilation/min / 5L perfusion/min = 0.8.", "What is V/Q ratio? Normal?"),
    (1778251562601, "Increases blood pressure. Its metabolite acts as an agonist at the alpha 1 adrenergic receptors in arterial and venous vasculature.", "What does Midodrine do?"),
    (1778251562603, "100% FiO₂ until carboxyhemoglobin level is &lt;10%. Hyperbaric oxygen chamber if available.", "Treatment for carbon monoxide poisoning?"),
    (1778251562605, "- tubing — no dependent loops- keep drainage chamber lower than chest- tidaling in water seal chamber (raising with inspiration, lowering with expiration) may occur with deep breathing- air leak: bubbling in the water seal chamber is not normal- suction control chamber: gauge or water level determines the amount of suction, not the wall suction source- clamp only when changing the system. Clamping cuts off negative pressure, lung may recollapse", "Key things about chest tube management?"),
    (1778251562607, "- coughing- secretions (suction)- aspiration- kinked tube- bronchospasm- pneumothorax", "Causes of high pressure alarms on vents?"),
    (1778251562609, "When the blood pressure cuff is inflated, the brachial artery is occluded, this induces spasms of the muscles in the hand and forearm. This occurs with hypocalcemia.", "What is trousseau's sign?"),
    (1778251562611, "1. A pt with a splenectomy has reduced immune function because the spleen is thought to \"filter\" the blood.\n2. Signs of splenic rupture: Kehr's sign (slarp left shoulder pain, worse with deep breathing), and abdominal distension with absent bowel tones", "What two things should you know about the spleen?"),
    (1778251562613, "- Optimize pt position by putting bed in reverse trendelenburg with HOB &lt;20 degrees\n- Loosen constrictive clothing\n- manage pain and agitation\n- prevent overhydration\n- Place NG to LIS to decompress\n- Optimize stool management, asses for impaction, consider RT or enema\n\n> 20 is considered abdominal compartment syndrome. Decompression surgery may be indicated.", "Treatment for IAP >12-15? >20?"),
    (1778251562615, "- Malabsorption: vitamin deficiences (protein, calcium, iron, B-12, folate)\n- wound related\n- enteric leakage\n- gallstones (52% will have gallstones within 1 year)\n- Bowel obstruction secondary to scar tissue or kink", "Complications of bariatric surgery?"),
    (1778251562617, "- Decreased blood flow to the mesenteric vessels\n- prolonged ischemia\n- edema to the intestinal wall\n- full thickness necrosis\n- perforation, peritonitis", "Pathophysiology of bowel infarction?"),
    (1778251562619, "- ABCs\n- fluids\n- gastric decompression with NG to LIS\n- manage pain\n- bowel resection with debridement of necrotic tissue\n- monitor for sepsis", "Tx for bowel infarction?"),
    (1778251562621, "- ABCs\n- gastric decompression with NG tube\n- treat pain\n- antibiotics, blood cultures\n- monitor for infection\n- surgery: repair perf. may require temporary bowel diversion. antibiotic lavage during surgery", "Treatment of bowel perf?"),
    (1778251562623, "Enteral: adequate metabolic support, maintains gut structure and function, prevents translocation of bacteria and gut toxins, associated with fewer complications, cheaper.", "Enteral vs parenteral nutrition?"),
    (1778251562625, "- Maintain HOB 30–45\n- Ensure NG/OG is in the right place\n- Check the tube location q4 hours after feedings are started: observe for changes in external length of tube\n- IF SUSPECTED HIGH RESIDUAL check residual. Do not check routinely. Large volume, hold tube feeds and consult provider. check BG.", "Nursing considerations for enteral nutrition?"),
    (1778251562627, "- >20%: chest tube, reestablish negative pleural pressure, supplemental O2, tx pain.\n- &lt;20%: O2, monitor for reexpansion, if they additionally have underlying lung disease, they may need a chest tube.", "Treatment for a simple pneumothorax?"),
    (1778251562629, "Persistent tachycardia, agitation, restless, nausea, temor, headaches", "Clonidine withdrawal symptoms?"),
    (1778251562631, "Rewarming causes rebound hyperkalemia. Stop all potassium administration 8 hours prior to rewarming.", "Key consideration for rewarming after targeted temperature control?"),
    (1778251562633, "- III, VI, VIII\n- After clearing C-spine, patients eyes are held open and eye movement is watched as the head is rapidly trned from side to side. Normal is if the eyes move in the opposite direction of the head turn. \"It's good to be a doll.\"", "What cranial nerves does 'doll's eyes' assess?"),
    (1778251562635, "- midbrain problem: hyperventilation\n- Pontine problem: apneustic breathing (prolonged inspiration and pause at full inspiration)\n- Medulla probelm: ataxic breathing (irregular variability of breathing effort and timing), leads to respiratory arrest", "Respiratory patterns with brain stem abnormalities?"),
    (1778251562637, "- Hydrocephalus may occur since the chorionic cilli in the subarachnoid space reabsorb CSF. If the chorionic villi are blocked, CSF may not be able to be reabsorbed\n- Rebleed and vasospasm: noted by change in LOC.", "Potential complications of SAH?"),
    (1778251562639, "These are hypotonic solutions, so they would rapidly leave the vascular compartment and go intracellular. This cell \"swelling\" would exacerbate the problem.", "Why would 0.45 NS and D5W be contraindicated for increased ICP?"),
    (1778251562641, "Epidural symptoms occur rapidly. Subdural may generate symptoms more slowly.", "Difference in acuity of epidural vs subdural hematomas?"),
    (1778251562643, "- Raccoon eyes- battles sign (ecchymosis at the back of ear)- rhinorrhea due to meningeal tear, don't blow nose!- otorrhea, fluid from ear due to meningeal tear- damage to cranial nerve I — loss of sense of smell", "Signs of basilar skull fx?"),
    (1778251562645, "- nuchal rigidity: flex pts head to chest, if pain and stiffness occur, pt is positive for nuchal rigidity- Brudzinskis sign: move pts chin to chest, if pts legs come up, the pt has a positive brudzinskis sign- Kernigs sign: move the pts leg up and out, if this causes pain in the neck and leg, the pt has positive kernigs sign", "Signs of meningeal irritation?"),
    (1778251562647, "- Ascending paralysis, usually symmetrical\n- Lumbar puncture may show protein in the CSF.\n- No alteration in consciousness", "Guillain-Barre syndrome?"),
    (1778251562649, "- within 24 hrs after last dose\n- anxiety, insomnia, restlessness, lawning, lacrimation, rhinorrhea, diaphoresis, vomiting, diarrhea, fever, chills, uscle spasms, tremor, tachycardia, HTN", "Signs of opioid withdrawal?"),
    (1778251562651, "- rupture of the posterior papillary muscle, resulting in a systolic murmur, loudest over the apical area of the chest wall. It's more common with an inferior MI because the posterior papillary muscle is supplied by the RCA.", "Symptom common with acute inferior MI?"),
    (1778251562653, "3.4–4.5\nMuscle weakness (may affect diaphragm and result in hypoventilation), constipation, depressed deep tendon reflexes.", "How does hypophosphatemia present?"),
    (1778251562655, "BIncreased oxygen saturation in the pulmonary artery and the right ventricle because blood from the left side of the heart is being shunted to the right.", "Positive sign that a VSD has occurred?"),
    (1778251562657, "I.e. Digoxin.\nThey inhibit the sodium potassium ATPase pump in the heart. This creates:\n- Positive inotropic action\n- Negative chronotropic action: decreased HR\n- Negative dromotropic action (reduces speed of electrical imulse through AV node)", "What are cardiac glycosides?"),
    (1778251562659, "Large volume fluid resuscitation, which can cause third spacing of fluid, leading to tissue edema.", "What intervention is linked to abdominal compartment syndrome?"),
    (1778251562661, "It causes increased sodium and BUN due to facticious dehydration.", "Change in sodium and BUN with bleeding?"),
    (1778251562663, "Happens with inferior MI so they can be hypotensive. Systolic murmur at apex of heart", "Symptoms of papillary muscle rupture?"),
    (1778251562665, "There's a membrane rupture, stop treatment and disconnect the circuit.", "Blood in effluent bag during CRRT?"),
    (1778251562667, "Spironolactone. They need a potassium sparing diuretic because hypokalemia can worsen ammonia (triggers ammonia production in the kidneys). You would not rehydrate with LR because it has lactate in it which can worsen ammonia. 0.9 NS is preferred", "Treat ascites with hepatic failure?"),
    (1778251562669, "A: Within 24 hours of sustained treatment", "How quickly do people develop tolerance to NTG?"),
    (1778251562671, "Prosthetic valve endocarditis", "Post-valve replacement: fever, new murmur, positive blood cultures..."),
    (1778251562673, "Assess and correct oxygenation", "Agitated, pacing patient with hypoxia: first intervention?"),
    (1778251562675, "Explicit patient permission and need-to-know basis.", "Patient requests confidentiality about a diagnosis..."),
    (1778251562677, "Educate on risks/ineffectiveness and propose evidence-based alternatives.", "Patient demands ineffective antibiotic..."),
    (1778251562679, "Follow policy, clarify with the prescriber, and escalate per chain-of-command.", "Team orders conflict with hospital policy?"),
    (1778251562681, "Patient self-report unless unsafe; reassess after intervention.", "Patient states 10/10 pain but appears calm..."),
    (1778251562683, "Coaching, reassurance, and synchronizing mask breaks with breathing.", "Patient with severe anxiety during NIV?"),
    (1778251562685, "Frequent circulation, skin, nutrition, toileting, and risk reassessment with time-limits.", "Key reassessment requirement after restraints applied?"),
    (1778251562687, "Qualified medical interpreter, not family, except emergencies.", "When language barriers exist, which interpreter?"),
    (1778251562689, "Collaborate to adjust times safely or obtain exemptions when indicated.", "Patient observes fasting; medication scheduling?"),
    (1778251562691, "Use correct names/pronouns and assess needs without assumptions.", "Action demonstrating inclusion for LGBTQ+ patients?"),
    (1778251562693, "Patient explains the plan in their own words to confirm understanding.", "Teach-back is best described as?"),
    (1778251562695, "Hands-on practice with return demonstration and printed steps.", "Best way to individualize education for new trach caregiver?"),
    (1778251562697, "Clinicians and patient/surrogate jointly choose options aligned with values.", "What defines shared decision-making in the ICU?"),
    (1778251562699, "Objective triggers (vitals, EWS) and concern for acute deterioration.", "Rapid response activation should be based on?"),
    (1778251562701, "Invite to rounds and encourage questions using plain language.", "What action supports family as part of the team?"),
    (1778251562703, "Sensitivity, specificity, predictive values, likelihood ratios.", "Statistics that evaluate a screening test's accuracy?"),
    (1778251562705, "- aortic cross-clamping → heart is stopped\n- the longer the bypass time, the more bleeding there is & complications post — op", "What happens during cardiopulmonary bypass?"),
    (1778251562707, "De-escalation and ensuring safety", "Confused patient pulls at IV lines and shouts. Priority?"),
    (1778251562709, "Ensure safety and notify mental health team", "Patient with depression says 'I want to end it all.' Priority?"),
    (1778251562711, "bolus: 20–80 mg IV (max 200 mg single dose in resistant cases) | continuous: 0.5–1 mg/kg/h (DOSE-CHF: equivalent outcomes to bolus) | furosemide 40 mg = bumetanide 1 mg = torsemide 20 mg | continuous infusion = more consistent natriuresis, less peak trough variability, possible lower ototoxicity risk\n→ PHARM KEY: Infuse bolus dose over 1–4 min (≤4 mg/min IV to avoid ototoxicity). Faster infusion rates = increased cochlear toxicity risk. Monitor: urine output hourly, K⁺, Mg²⁺, Na⁺ every 6–8h with aggressive diuresis.", "Furosemide ICU dosing: IV bolus, continuous infusion, dose equivalent..."),
    (1778251562713, "potassium (K⁺) — inhibition of NKCC2 → loss of K⁺ in collecting duct | magnesium (Mg²⁺) — dependent on Na⁺ gradient | hypokalemia → arrhythmias in cardiac patients; hypomagnesemia → K⁺ CANNOT BE CORRECTED regardless of replacement amount (Mg required for Na/K-ATPase function)\n→ PHARM KEY: The K+/Mg²⁺ connection: never just replace K⁺ without checking Mg²⁺. If Mg is low, check and replace first — K⁺ correction will fail until Mg is adequate.", "Furosemide always depletes ___ and ___ — nurse ALWAYS monitors..."),
    (1778251562715, "hypertonic saline creates osmotic gradient WITHOUT diuresis (mannitol → urinary loss of Na⁺/water) → can correct hyponatremia while reducing ICP | less rebound edema, safer in hypovolemia (mannitol dehydrates), corrects hyponatremia simultaneously | patient is hemodynamically unstable or hyponatremic\n→ PHARM KEY: 23.4% NaCl via central line for acute herniation (30 mL bolus). 3% NaCl for ongoing ICP management. Correct Na⁺ ≤10 mEq/L per 24h to prevent central pontine myelinolysis (osmotic demyelination).", "Hypertonic saline (3% NaCl) for increased ICP..."),
    (1778436692044, "FIRST: BLOOD CULTURES (2 sets from 2 different sites) — must be obtained BEFORE antibiotics to preserve the ability to identify the causative organism and guide de-escalation\n| Why cultures first: once antibiotics are in the blood, organisms begin dying → culture bottles yield false-negative results → 7–14 days of broad-spectrum empiric therapy instead of targeted therapy guided by sensitivity data. The 5-minute delay to draw cultures is clinically trivial compared to this consequence.\n| ANTIBIOTICS within 1 HOUR of sepsis recognition — broad-spectrum empiric coverage targeting the most likely pathogens based on suspected source:\n  - Unknown source/septic shock: vancomycin (MRSA) + piperacillin-tazobactam (gram-negatives including Pseudomonas) ± antifungal if immunocompromised or recent antibiotics\n  - Pneumonia (CAP): beta-lactam + macrolide/azithromycin or respiratory fluoroquinolone\n  - HAP/VAP: vancomycin + cefepime or piperacillin-tazobactam\n| Mortality increases approximately 7–10% per hour of antibiotic delay in septic shock — one of the most time-sensitive drug administrations in medicine\n→ CCRN KEY: Blood cultures before antibiotics is an ORDER, not a suggestion. The nurse who administers antibiotics before drawing cultures has eliminated the possibility of organism identification. Even 5–10 minutes of urgency should not reverse this order.\n→ MASTERY NOTE: Antibiotic de-escalation (narrowing coverage once cultures return with sensitivities) is a stewardship goal — it requires having culture data. Cultures drawn after antibiotics are negative 30–40% more often than pre-antibiotic cultures. The broad-spectrum empiric regimen costs more, has more side effects, and promotes resistance. Pre-antibiotic cultures make de-escalation possible.", "Septic Shock 1-Hour Bundle [Pos 1/2] — FIRST action before antibiotics..."),
    (1778436692047, "(1) BLOOD CULTURES (2 sets) — FIRST, before antibiotics; preserves organism identification for targeted therapy and de-escalation\n| (2) BROAD-SPECTRUM ANTIBIOTICS within 1 HOUR — empiric coverage based on suspected source; every hour of delay ↑ mortality ~7–10%\n| (3) 30 mL/kg IV CRYSTALLOID bolus — if hypotension (SBP &lt;90 mmHg) OR lactate ≥4 mmol/L; NS or LR acceptable; complete within 3h of identification; reassess fluid responsiveness after initial bolus (don't give more fluid if patient is not fluid-responsive)\n| (4) VASOPRESSORS if MAP &lt;65 mmHg persists despite initial fluid bolus — Norepinephrine is first-line vasopressor in septic shock (alpha-adrenergic → SVR ↑; beta-adrenergic → maintains CO); target MAP ≥65 mmHg\n| (5) REASSESS FLUID RESPONSIVENESS — PLR (passive leg raise with LVOT VTI ≥10% change = fluid responsive) OR echocardiography. Test: PLR — positive PLR → give more fluid; negative PLR → vasopressors/investigate cause\n→ CCRN KEY: The 1-hour bundle is the operationalized version of the \"Hour-1 Bundle\" from SSC 2018 guidelines. All five elements should be initiated simultaneously when possible. The nurse manages elements 1, 3, and 5 (cultures, fluid, and reassessment); the physician orders elements 2 and 4.\n→ MASTERY NOTE: Lactate ≥4 mmol/L is a critical threshold in sepsis — it indicates tissue hypoperfusion (anaerobic metabolism) even if blood pressure appears acceptable. Cryptic shock (lactate ≥4 with normal BP) carries similar mortality to overt septic shock and requires the same aggressive initial management. Repeat lactate at 2 hours: failure to clear by ≥10% is a poor prognostic sign.", "[Synthesis] Septic Shock 1-Hour Bundle all 5 elements..."),
    (1778480387928, "CaO₂ (arterial oxygen content) = (Hgb × 1.34 × SaO₂/100) + (0.003 × PaO₂)\n| Dissolved O₂ (0.003 × PaO₂) contributes only ~30 mL/min at PaO₂ 100 mmHg = &lt;3% of total DO₂. Hgb-bound O₂ carries >97%.\n| Normal DO₂ ≈ 950–1000 mL/min (CO 5 L/min × CaO₂ ~20 mL/dL × 10)\n| Adjusting Hgb slider: each 1 g/dL change in Hgb changes DO₂ by ~134 mL/min (1.34 × SaO₂/100 × CO × 10). A larger absolute effect than most interventions.\n→ CCRN KEY: The 1.34 constant = mL O₂ bound per gram of Hgb when fully saturated. This is why Hgb is the dominant term — it is the carrying capacity. Hgb 7 vs Hgb 14 at the same SaO₂ and CO = half the DO₂. SpO₂ looks identical in both patients.\n→ MASTERY NOTE: Supplemental O₂ is often the first intervention for 'low sats' — but raising PaO₂ from 100 → 200 mmHg only adds ~30 mL/min to DO₂ (dissolved term only). This is why hyperoxia adds negligible DO₂ benefit in patients with normal or near-normal SpO₂. The interventions that actually matter: ↑Hgb (transfusion), ↑CO (inotropes, afterload reduction), ↑SaO₂ from pathologically low levels.", "DO2 = CO x ___ x 10. Component contributing LEAST..."),
    (1778480387931, "Critical threshold: approximately 330 mL/min — below this, O₂ consumption can no longer be sustained by increased extraction (maximum extraction ratio ~70–75% reached). Tissues switch to anaerobic metabolism.\n| O₂ consumption becomes SUPPLY-DEPENDENT — VO₂ falls proportionally with DO₂ instead of being demand-determined. Each mL of O₂ delivery reduction causes additional O₂ debt.\n| With CO 3.5, Hgb 7.2, SaO₂ 96%: DO₂ ≈ 3.5 × (7.2 × 1.34 × 0.96) × 10 ≈ 324 mL/min — AT or BELOW the critical threshold. Despite 'acceptable' vital signs, this patient has minimal O₂ reserve.\n| Clinical marker: ELEVATED LACTATE (>2 mmol/L) confirms anaerobic metabolism. The cells produce lactate when they cannot meet ATP demand aerobically. Lactate >4 mmol/L = significant O₂ debt.\n→ CCRN KEY: Lactate CLEARANCE (not just single value) is the resuscitation endpoint: ≥10% clearance per 2 hours confirms DO₂ has been restored above the critical threshold. Failure to clear despite hemodynamically 'normalized' parameters = DO₂ still inadequate.\n→ MASTERY NOTE: ScvO₂ and lactate together describe the O₂ supply-demand relationship: ScvO₂ ↓ (tissues extracting more) → approaching critical threshold → lactate ↑ (anaerobic) → DO₂ below critical threshold. The progression from ScvO₂ 55% → 48% → lactate 3.2 → 5.8 is the trajectory of deterioration. Intervene at ScvO₂ drop, before lactate rises.", "Critical DO2 threshold ~___. Below this, O2 consumption becomes ___ dependent..."),
    (1778480387934, "Current DO₂ ≈ 3.2 × (6.8 × 1.34 × 0.97) × 10 ≈ 282 mL/min — BELOW critical threshold (330). Lactate 3.6 confirms active anaerobic metabolism.\n| Intervention A (transfuse Hgb → 9.5): DO₂ ≈ 3.2 × (9.5 × 1.34 × 0.97) × 10 ≈ 394 mL/min (+112 mL/min)\n| Intervention B (dobutamine CO → 4.8): DO₂ ≈ 4.8 × (6.8 × 1.34 × 0.97) × 10 ≈ 423 mL/min (+141 mL/min)\n| Dobutamine raises DO₂ more in the calculation — but NOT the only consideration:\n  Transfusion: immediate effect, corrects the true deficit (anemia), no ↑HR or myocardial stress, evidence-based threshold (Hgb &lt;7 for non-cardiac; &lt;8 for cardiac post-op)\n  Dobutamine: ↑HR → ↑myocardial O₂ demand → risk in post-MI or post-CABG; arrhythmia risk; ↑VO₂ partially offsets ↑DO₂ gain\n→ CCRN KEY: In post-op anemic patients: TRANSFUSE — it corrects the anatomical cause of low DO₂ without cardiac stress. Dobutamine treats pump inadequacy, not anemia. TRICC trial: Hgb threshold 7 for stable ICU (non-cardiac); 8 for cardiac/hemodynamically unstable. The post-op setting with anemia is a transfusion indication.\n→ MASTERY NOTE: The DO₂ equation reveals WHICH lever to pull, but clinical context determines which is SAFE. The equation is a decision support tool — not a pure optimization algorithm. Choosing the intervention that most safely restores DO₂ above 330 mL/min while minimizing VO₂ increase is the therapeutic goal.", "Post-op patient: Hgb 6.8, SaO2 97%, CO 3.2, lactate 3.6. DO2 = ?..."),
    (1778808560000, ">=10% reduction at 2h | >=20% reduction at 6h | The green curve on the chart shows adequate clearance crossing below 4 mmol/L (shock threshold) by ~4 hours; the red curve fails to clear, remaining in the shock range despite adequate MAP.\n→ CCRN KEY: Lactate clearance is superior to MAP alone as a resuscitation endpoint -- patients can have occult hypoperfusion with MAP >65. Clearance &lt;10% at 2h warrants reassessment of fluid responsiveness and source control.\n→ MASTERY NOTE: Type B lactic acidosis (liver failure, metformin toxicity, thiamine deficiency) impairs clearance without tissue hypoperfusion -- correlate with ScvO2 &gt;70% and clinical exam before escalating vasopressors.", "SSC 2021 targets lactate clearance ___ at 2h and ___ at 6h..."),
    (1778808560003, "~6.8% at 6h (target >=20%) | Persistent occult hypoperfusion -- inadequate resuscitation despite acceptable hemodynamic endpoints | Next: reassess fluid responsiveness (PLR or POCUS), check ScvO2 (target >70%), confirm source control, optimize vasopressors.\n→ CCRN KEY: MAP >=65 + UO >=0.5 mL/kg/hr do NOT guarantee adequate perfusion. Lactate non-clearance at 6h doubles 28-day mortality independent of other endpoints in septic shock.\n→ MASTERY NOTE: ScvO2 &gt;80% + non-clearing lactate = suspect cytopathic hypoxia (mitochondrial dysfunction). Cells cannot extract delivered O2 -- rising lactate reflects cellular hypoxia, not low-flow state. More fluid or vasopressors will not correct this.", "Septic shock initial lactate 7.4, at 6h repeat 6.9. Clearance = ?..."),
    (1778808560006, "Type B lactic acidosis -- most likely hepatic clearance failure (shock liver / ischemic hepatopathy) in the post-arrest state | Check LFTs, INR, bilirubin; shock liver peaks at 24-72h post-arrest. Also: thiamine (B1) deficiency (impairs pyruvate dehydrogenase), epinephrine infusion (drives glycolysis), metformin (if not held).\n→ CCRN KEY: Elevated lactate + improving hemodynamics + adequate ScvO2 = suspect impaired hepatic clearance, not ongoing tissue hypoperfusion. The liver clears ~70% of circulating lactate.\n→ MASTERY NOTE: Thiamine 200 mg IV should be given empirically in any post-arrest or septic patient with non-clearing lactate -- it is the essential cofactor for pyruvate dehydrogenase (pyruvate -&gt; acetyl-CoA instead of lactate). Safe, inexpensive, and effects are seen within minutes.", "Post-arrest patient: MAP 72, ScvO2 78%, adequate UO, lactate 8.1 no clearance 8h..."),
    (1778808560009, "~300-330 mL/min/m2 | VO2 plateaus at ~200-220 mL/min/m2 regardless of further DO2 increases (supply-independent region) | Below critical DO2: anaerobic metabolism begins, lactate rises, organ dysfunction develops.\n→ CCRN KEY: DO2 = CI x CaO2 x 10. Optimize all three components: Hgb/SaO2 (CaO2), cardiac output (CI), and arterial oxygen content. Targeting ScvO2 &gt;70% is a surrogate for adequate supply-demand balance above critical DO2.\n→ MASTERY NOTE: The inflection point (critical DO2) varies by patient and metabolic state -- fever, shivering, and pain increase VO2 demand and shift the critical threshold higher. Temperature management and analgesia reduce VO2 demand in critically ill patients.", "DO2/VO2 curve: O2 consumption becomes supply-dependent below critical DO2 of ~___..."),
    (1778808560012, "Pathological supply dependency | Microvascular shunting + mitochondrial dysfunction (cytopathic hypoxia) -- cells cannot extract or utilize delivered O2 | ScvO2 may be falsely elevated (>75-80%) -- venous blood returns O2-rich because cells cannot use it, NOT because delivery is excessive.\n→ CCRN KEY: High ScvO2 in septic shock does NOT reliably indicate adequate resuscitation. Use lactate trajectory, base deficit, and clinical perfusion markers alongside ScvO2. O2 extraction ratio (OER = VO2/DO2) is normally 25-30%; in cytopathic hypoxia OER may be &lt;20% despite cellular hypoxia.\n→ MASTERY NOTE: The sepsis curve in the chart stays supply-dependent across the entire DO2 range -- no plateau forms. This is pathognomonic of distributive shock with extraction failure, not simple low-output states where increasing CO or Hgb would restore the plateau.", "In sepsis, DO2/VO2 curve shows ___, meaning VO2 continues rising..."),
    (1778808560015, "Pathological O2 supply dependency with cytopathic hypoxia -- adequate delivery, impaired cellular utilization | Priority: rule out and drain undrained infectious source (definitive source control), optimize antibiotic timing and spectrum, thiamine IV empirically, avoid vasopressor escalation as the sole response to rising lactate when CI is already adequate.\n→ CCRN KEY: Do NOT interpret ScvO2 &gt;80% as 'all is well' when lactate is rising. Dysregulated O2 extraction is a defining feature of late septic shock and does not respond to more fluid or vasopressors -- treat the underlying cause (antibiotics + source control).\n→ MASTERY NOTE: Lactate &gt;4 mmol/L + ScvO2 &gt;80% + CI &gt;4 L/min/m2 = cytopathic hypoxia triad until proven otherwise. This pattern carries higher mortality than low-DO2 shock. Organ support (renal replacement, ventilator optimization) and metabolic resuscitation (thiamine, ascorbic acid) are the relevant levers -- not further DO2 augmentation.", "Septic patient: CI 4.8, Hgb 10, SaO2 98%, ScvO2 84%, lactate 6.2 rising..."),
]

print(f"{'NID':<16} {'Count':>5}  Front (truncated)")
print("-" * 80)
over300 = []
le300 = []
for nid, back, front in notes:
    c, _ = vis_count(back)
    flag = " <<<" if c > 300 else ""
    print(f"{nid:<16} {c:>5}{flag}  {front[:55]}")
    if c > 300:
        over300.append((nid, c, front[:55]))
    else:
        le300.append((nid, c))

print(f"\n--- SUMMARY ---")
print(f"Total notes: {len(notes)}")
print(f"Notes >300 chars: {len(over300)}")
print(f"Notes <=300 chars: {len(le300)}")
print()
print("NOTES OVER 300 chars:")
for nid, c, front in over300:
    print(f"  NID {nid}: {c} chars")
    print(f"    {front}")
